/** Errori di business: codice costante, mai Error generici. */
export class DomainError extends Error {
  constructor(
    public code: ErrorCode,
    message?: string,
  ) {
    super(message ?? code);
    this.name = 'DomainError';
  }
}

export const ERR = {
  PROGRAM_NOT_FOUND: 'PROGRAM_NOT_FOUND',
  PROGRAM_HAS_SESSIONS: 'PROGRAM_HAS_SESSIONS',
  DAY_NOT_FOUND: 'DAY_NOT_FOUND',
  PROGRAM_EXERCISE_NOT_FOUND: 'PROGRAM_EXERCISE_NOT_FOUND',
  EXERCISE_NOT_FOUND: 'EXERCISE_NOT_FOUND',
  EXERCISE_NAME_EXISTS: 'EXERCISE_NAME_EXISTS',
  EXERCISE_HAS_HISTORY: 'EXERCISE_HAS_HISTORY',
  EXERCISE_IN_USE: 'EXERCISE_IN_USE',
  MUSCLE_GROUP_NOT_FOUND: 'MUSCLE_GROUP_NOT_FOUND',
  MUSCLE_GROUP_NAME_EXISTS: 'MUSCLE_GROUP_NAME_EXISTS',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_ACTIVE: 'SESSION_ALREADY_ACTIVE',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_EMPTY: 'SESSION_EMPTY',
  SESSION_NOT_EMPTY: 'SESSION_NOT_EMPTY',
  SESSION_EXERCISE_NOT_FOUND: 'SESSION_EXERCISE_NOT_FOUND',
  SET_LOG_NOT_FOUND: 'SET_LOG_NOT_FOUND',
  INVALID_NAME: 'INVALID_NAME',
  INVALID_WEIGHT: 'INVALID_WEIGHT',
  INVALID_REPS: 'INVALID_REPS',
  INVALID_RIR: 'INVALID_RIR',
  INVALID_REST: 'INVALID_REST',
  INVALID_SETS: 'INVALID_SETS',
  INVALID_STEP: 'INVALID_STEP',
  INVALID_TIME: 'INVALID_TIME',
  BACKUP_INVALID: 'BACKUP_INVALID',
  BACKUP_FUTURE_VERSION: 'BACKUP_FUTURE_VERSION',
} as const;

export type ErrorCode = (typeof ERR)[keyof typeof ERR];
